/*
 * ${product.name.full} Admin REST API
 * This is a REST API reference for the ${product.name.full} Admin REST API.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.mbo.keycloak.admin.api.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.mbo.keycloak.admin.api.dto.AccessTokenAccessDto;
import dev.mbo.keycloak.admin.api.dto.AccessTokenAuthorizationDto;
import dev.mbo.keycloak.admin.api.dto.AccessTokenCertConfDto;
import dev.mbo.keycloak.admin.api.dto.AddressClaimSetDto;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * AccessTokenDto
 */
@JsonPropertyOrder({
  AccessTokenDto.JSON_PROPERTY_ACR,
  AccessTokenDto.JSON_PROPERTY_ADDRESS,
  AccessTokenDto.JSON_PROPERTY_ALLOWED_ORIGINS,
  AccessTokenDto.JSON_PROPERTY_AT_HASH,
  AccessTokenDto.JSON_PROPERTY_AUTH_TIME,
  AccessTokenDto.JSON_PROPERTY_AUTHORIZATION,
  AccessTokenDto.JSON_PROPERTY_AZP,
  AccessTokenDto.JSON_PROPERTY_BIRTHDATE,
  AccessTokenDto.JSON_PROPERTY_C_HASH,
  AccessTokenDto.JSON_PROPERTY_CATEGORY,
  AccessTokenDto.JSON_PROPERTY_CLAIMS_LOCALES,
  AccessTokenDto.JSON_PROPERTY_CNF,
  AccessTokenDto.JSON_PROPERTY_EMAIL,
  AccessTokenDto.JSON_PROPERTY_EMAIL_VERIFIED,
  AccessTokenDto.JSON_PROPERTY_EXP,
  AccessTokenDto.JSON_PROPERTY_FAMILY_NAME,
  AccessTokenDto.JSON_PROPERTY_GENDER,
  AccessTokenDto.JSON_PROPERTY_GIVEN_NAME,
  AccessTokenDto.JSON_PROPERTY_IAT,
  AccessTokenDto.JSON_PROPERTY_ISS,
  AccessTokenDto.JSON_PROPERTY_JTI,
  AccessTokenDto.JSON_PROPERTY_LOCALE,
  AccessTokenDto.JSON_PROPERTY_MIDDLE_NAME,
  AccessTokenDto.JSON_PROPERTY_NAME,
  AccessTokenDto.JSON_PROPERTY_NBF,
  AccessTokenDto.JSON_PROPERTY_NICKNAME,
  AccessTokenDto.JSON_PROPERTY_NONCE,
  AccessTokenDto.JSON_PROPERTY_OTHER_CLAIMS,
  AccessTokenDto.JSON_PROPERTY_PHONE_NUMBER,
  AccessTokenDto.JSON_PROPERTY_PHONE_NUMBER_VERIFIED,
  AccessTokenDto.JSON_PROPERTY_PICTURE,
  AccessTokenDto.JSON_PROPERTY_PREFERRED_USERNAME,
  AccessTokenDto.JSON_PROPERTY_PROFILE,
  AccessTokenDto.JSON_PROPERTY_REALM_ACCESS,
  AccessTokenDto.JSON_PROPERTY_S_HASH,
  AccessTokenDto.JSON_PROPERTY_SCOPE,
  AccessTokenDto.JSON_PROPERTY_SESSION_STATE,
  AccessTokenDto.JSON_PROPERTY_SID,
  AccessTokenDto.JSON_PROPERTY_SUB,
  AccessTokenDto.JSON_PROPERTY_TRUSTED_CERTS,
  AccessTokenDto.JSON_PROPERTY_TYP,
  AccessTokenDto.JSON_PROPERTY_UPDATED_AT,
  AccessTokenDto.JSON_PROPERTY_WEBSITE,
  AccessTokenDto.JSON_PROPERTY_ZONEINFO
})
@JsonTypeName("AccessToken")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AccessTokenDto {
  public static final String JSON_PROPERTY_ACR = "acr";
  private String acr;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private AddressClaimSetDto address;

  public static final String JSON_PROPERTY_ALLOWED_ORIGINS = "allowed-origins";
  private List<String> allowedOrigins = null;

  public static final String JSON_PROPERTY_AT_HASH = "at_hash";
  private String atHash;

  public static final String JSON_PROPERTY_AUTH_TIME = "auth_time";
  private Long authTime;

  public static final String JSON_PROPERTY_AUTHORIZATION = "authorization";
  private AccessTokenAuthorizationDto authorization;

  public static final String JSON_PROPERTY_AZP = "azp";
  private String azp;

  public static final String JSON_PROPERTY_BIRTHDATE = "birthdate";
  private String birthdate;

  public static final String JSON_PROPERTY_C_HASH = "c_hash";
  private String cHash;

  /**
   * Gets or Sets category
   */
  public enum CategoryEnum {
    INTERNAL("INTERNAL"),
    
    ACCESS("ACCESS"),
    
    ID("ID"),
    
    ADMIN("ADMIN"),
    
    USERINFO("USERINFO"),
    
    LOGOUT("LOGOUT"),
    
    AUTHORIZATION_RESPONSE("AUTHORIZATION_RESPONSE");

    private String value;

    CategoryEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CategoryEnum fromValue(String value) {
      for (CategoryEnum b : CategoryEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CATEGORY = "category";
  private CategoryEnum category;

  public static final String JSON_PROPERTY_CLAIMS_LOCALES = "claims_locales";
  private String claimsLocales;

  public static final String JSON_PROPERTY_CNF = "cnf";
  private AccessTokenCertConfDto cnf;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_EMAIL_VERIFIED = "email_verified";
  private Boolean emailVerified;

  public static final String JSON_PROPERTY_EXP = "exp";
  private Long exp;

  public static final String JSON_PROPERTY_FAMILY_NAME = "family_name";
  private String familyName;

  public static final String JSON_PROPERTY_GENDER = "gender";
  private String gender;

  public static final String JSON_PROPERTY_GIVEN_NAME = "given_name";
  private String givenName;

  public static final String JSON_PROPERTY_IAT = "iat";
  private Long iat;

  public static final String JSON_PROPERTY_ISS = "iss";
  private String iss;

  public static final String JSON_PROPERTY_JTI = "jti";
  private String jti;

  public static final String JSON_PROPERTY_LOCALE = "locale";
  private String locale;

  public static final String JSON_PROPERTY_MIDDLE_NAME = "middle_name";
  private String middleName;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NBF = "nbf";
  private Long nbf;

  public static final String JSON_PROPERTY_NICKNAME = "nickname";
  private String nickname;

  public static final String JSON_PROPERTY_NONCE = "nonce";
  private String nonce;

  public static final String JSON_PROPERTY_OTHER_CLAIMS = "otherClaims";
  private Map<String, Object> otherClaims = null;

  public static final String JSON_PROPERTY_PHONE_NUMBER = "phone_number";
  private String phoneNumber;

  public static final String JSON_PROPERTY_PHONE_NUMBER_VERIFIED = "phone_number_verified";
  private Boolean phoneNumberVerified;

  public static final String JSON_PROPERTY_PICTURE = "picture";
  private String picture;

  public static final String JSON_PROPERTY_PREFERRED_USERNAME = "preferred_username";
  private String preferredUsername;

  public static final String JSON_PROPERTY_PROFILE = "profile";
  private String profile;

  public static final String JSON_PROPERTY_REALM_ACCESS = "realm_access";
  private AccessTokenAccessDto realmAccess;

  public static final String JSON_PROPERTY_S_HASH = "s_hash";
  private String sHash;

  public static final String JSON_PROPERTY_SCOPE = "scope";
  private String scope;

  public static final String JSON_PROPERTY_SESSION_STATE = "session_state";
  private String sessionState;

  public static final String JSON_PROPERTY_SID = "sid";
  private String sid;

  public static final String JSON_PROPERTY_SUB = "sub";
  private String sub;

  public static final String JSON_PROPERTY_TRUSTED_CERTS = "trusted-certs";
  private List<String> trustedCerts = null;

  public static final String JSON_PROPERTY_TYP = "typ";
  private String typ;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private Long updatedAt;

  public static final String JSON_PROPERTY_WEBSITE = "website";
  private String website;

  public static final String JSON_PROPERTY_ZONEINFO = "zoneinfo";
  private String zoneinfo;

  public AccessTokenDto() {
  }

  public AccessTokenDto acr(String acr) {
    
    this.acr = acr;
    return this;
  }

   /**
   * Get acr
   * @return acr
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ACR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAcr() {
    return acr;
  }


  @JsonProperty(JSON_PROPERTY_ACR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcr(String acr) {
    this.acr = acr;
  }


  public AccessTokenDto address(AddressClaimSetDto address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddressClaimSetDto getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(AddressClaimSetDto address) {
    this.address = address;
  }


  public AccessTokenDto allowedOrigins(List<String> allowedOrigins) {
    
    this.allowedOrigins = allowedOrigins;
    return this;
  }

  public AccessTokenDto addAllowedOriginsItem(String allowedOriginsItem) {
    if (this.allowedOrigins == null) {
      this.allowedOrigins = new ArrayList<>();
    }
    this.allowedOrigins.add(allowedOriginsItem);
    return this;
  }

   /**
   * Get allowedOrigins
   * @return allowedOrigins
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ALLOWED_ORIGINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAllowedOrigins() {
    return allowedOrigins;
  }


  @JsonProperty(JSON_PROPERTY_ALLOWED_ORIGINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowedOrigins(List<String> allowedOrigins) {
    this.allowedOrigins = allowedOrigins;
  }


  public AccessTokenDto atHash(String atHash) {
    
    this.atHash = atHash;
    return this;
  }

   /**
   * Get atHash
   * @return atHash
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_AT_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAtHash() {
    return atHash;
  }


  @JsonProperty(JSON_PROPERTY_AT_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAtHash(String atHash) {
    this.atHash = atHash;
  }


  public AccessTokenDto authTime(Long authTime) {
    
    this.authTime = authTime;
    return this;
  }

   /**
   * Get authTime
   * @return authTime
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_AUTH_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAuthTime() {
    return authTime;
  }


  @JsonProperty(JSON_PROPERTY_AUTH_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthTime(Long authTime) {
    this.authTime = authTime;
  }


  public AccessTokenDto authorization(AccessTokenAuthorizationDto authorization) {
    
    this.authorization = authorization;
    return this;
  }

   /**
   * Get authorization
   * @return authorization
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_AUTHORIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccessTokenAuthorizationDto getAuthorization() {
    return authorization;
  }


  @JsonProperty(JSON_PROPERTY_AUTHORIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthorization(AccessTokenAuthorizationDto authorization) {
    this.authorization = authorization;
  }


  public AccessTokenDto azp(String azp) {
    
    this.azp = azp;
    return this;
  }

   /**
   * Get azp
   * @return azp
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_AZP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAzp() {
    return azp;
  }


  @JsonProperty(JSON_PROPERTY_AZP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAzp(String azp) {
    this.azp = azp;
  }


  public AccessTokenDto birthdate(String birthdate) {
    
    this.birthdate = birthdate;
    return this;
  }

   /**
   * Get birthdate
   * @return birthdate
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_BIRTHDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBirthdate() {
    return birthdate;
  }


  @JsonProperty(JSON_PROPERTY_BIRTHDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBirthdate(String birthdate) {
    this.birthdate = birthdate;
  }


  public AccessTokenDto cHash(String cHash) {
    
    this.cHash = cHash;
    return this;
  }

   /**
   * Get cHash
   * @return cHash
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_C_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getcHash() {
    return cHash;
  }


  @JsonProperty(JSON_PROPERTY_C_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcHash(String cHash) {
    this.cHash = cHash;
  }


  public AccessTokenDto category(CategoryEnum category) {
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CategoryEnum getCategory() {
    return category;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategory(CategoryEnum category) {
    this.category = category;
  }


  public AccessTokenDto claimsLocales(String claimsLocales) {
    
    this.claimsLocales = claimsLocales;
    return this;
  }

   /**
   * Get claimsLocales
   * @return claimsLocales
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CLAIMS_LOCALES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClaimsLocales() {
    return claimsLocales;
  }


  @JsonProperty(JSON_PROPERTY_CLAIMS_LOCALES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClaimsLocales(String claimsLocales) {
    this.claimsLocales = claimsLocales;
  }


  public AccessTokenDto cnf(AccessTokenCertConfDto cnf) {
    
    this.cnf = cnf;
    return this;
  }

   /**
   * Get cnf
   * @return cnf
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CNF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccessTokenCertConfDto getCnf() {
    return cnf;
  }


  @JsonProperty(JSON_PROPERTY_CNF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCnf(AccessTokenCertConfDto cnf) {
    this.cnf = cnf;
  }


  public AccessTokenDto email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
  }


  public AccessTokenDto emailVerified(Boolean emailVerified) {
    
    this.emailVerified = emailVerified;
    return this;
  }

   /**
   * Get emailVerified
   * @return emailVerified
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_EMAIL_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEmailVerified() {
    return emailVerified;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
  }


  public AccessTokenDto exp(Long exp) {
    
    this.exp = exp;
    return this;
  }

   /**
   * Get exp
   * @return exp
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_EXP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExp() {
    return exp;
  }


  @JsonProperty(JSON_PROPERTY_EXP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExp(Long exp) {
    this.exp = exp;
  }


  public AccessTokenDto familyName(String familyName) {
    
    this.familyName = familyName;
    return this;
  }

   /**
   * Get familyName
   * @return familyName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFamilyName() {
    return familyName;
  }


  @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }


  public AccessTokenDto gender(String gender) {
    
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_GENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGender() {
    return gender;
  }


  @JsonProperty(JSON_PROPERTY_GENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGender(String gender) {
    this.gender = gender;
  }


  public AccessTokenDto givenName(String givenName) {
    
    this.givenName = givenName;
    return this;
  }

   /**
   * Get givenName
   * @return givenName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_GIVEN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGivenName() {
    return givenName;
  }


  @JsonProperty(JSON_PROPERTY_GIVEN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }


  public AccessTokenDto iat(Long iat) {
    
    this.iat = iat;
    return this;
  }

   /**
   * Get iat
   * @return iat
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getIat() {
    return iat;
  }


  @JsonProperty(JSON_PROPERTY_IAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIat(Long iat) {
    this.iat = iat;
  }


  public AccessTokenDto iss(String iss) {
    
    this.iss = iss;
    return this;
  }

   /**
   * Get iss
   * @return iss
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ISS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIss() {
    return iss;
  }


  @JsonProperty(JSON_PROPERTY_ISS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIss(String iss) {
    this.iss = iss;
  }


  public AccessTokenDto jti(String jti) {
    
    this.jti = jti;
    return this;
  }

   /**
   * Get jti
   * @return jti
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_JTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJti() {
    return jti;
  }


  @JsonProperty(JSON_PROPERTY_JTI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJti(String jti) {
    this.jti = jti;
  }


  public AccessTokenDto locale(String locale) {
    
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocale() {
    return locale;
  }


  @JsonProperty(JSON_PROPERTY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocale(String locale) {
    this.locale = locale;
  }


  public AccessTokenDto middleName(String middleName) {
    
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MIDDLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMiddleName() {
    return middleName;
  }


  @JsonProperty(JSON_PROPERTY_MIDDLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }


  public AccessTokenDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public AccessTokenDto nbf(Long nbf) {
    
    this.nbf = nbf;
    return this;
  }

   /**
   * Get nbf
   * @return nbf
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_NBF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNbf() {
    return nbf;
  }


  @JsonProperty(JSON_PROPERTY_NBF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNbf(Long nbf) {
    this.nbf = nbf;
  }


  public AccessTokenDto nickname(String nickname) {
    
    this.nickname = nickname;
    return this;
  }

   /**
   * Get nickname
   * @return nickname
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_NICKNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNickname() {
    return nickname;
  }


  @JsonProperty(JSON_PROPERTY_NICKNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNickname(String nickname) {
    this.nickname = nickname;
  }


  public AccessTokenDto nonce(String nonce) {
    
    this.nonce = nonce;
    return this;
  }

   /**
   * Get nonce
   * @return nonce
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_NONCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNonce() {
    return nonce;
  }


  @JsonProperty(JSON_PROPERTY_NONCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNonce(String nonce) {
    this.nonce = nonce;
  }


  public AccessTokenDto otherClaims(Map<String, Object> otherClaims) {
    
    this.otherClaims = otherClaims;
    return this;
  }

  public AccessTokenDto putOtherClaimsItem(String key, Object otherClaimsItem) {
    if (this.otherClaims == null) {
      this.otherClaims = new HashMap<>();
    }
    this.otherClaims.put(key, otherClaimsItem);
    return this;
  }

   /**
   * Get otherClaims
   * @return otherClaims
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_OTHER_CLAIMS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getOtherClaims() {
    return otherClaims;
  }


  @JsonProperty(JSON_PROPERTY_OTHER_CLAIMS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtherClaims(Map<String, Object> otherClaims) {
    this.otherClaims = otherClaims;
  }


  public AccessTokenDto phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhoneNumber() {
    return phoneNumber;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public AccessTokenDto phoneNumberVerified(Boolean phoneNumberVerified) {
    
    this.phoneNumberVerified = phoneNumberVerified;
    return this;
  }

   /**
   * Get phoneNumberVerified
   * @return phoneNumberVerified
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPhoneNumberVerified() {
    return phoneNumberVerified;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneNumberVerified(Boolean phoneNumberVerified) {
    this.phoneNumberVerified = phoneNumberVerified;
  }


  public AccessTokenDto picture(String picture) {
    
    this.picture = picture;
    return this;
  }

   /**
   * Get picture
   * @return picture
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PICTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPicture() {
    return picture;
  }


  @JsonProperty(JSON_PROPERTY_PICTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPicture(String picture) {
    this.picture = picture;
  }


  public AccessTokenDto preferredUsername(String preferredUsername) {
    
    this.preferredUsername = preferredUsername;
    return this;
  }

   /**
   * Get preferredUsername
   * @return preferredUsername
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PREFERRED_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreferredUsername() {
    return preferredUsername;
  }


  @JsonProperty(JSON_PROPERTY_PREFERRED_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreferredUsername(String preferredUsername) {
    this.preferredUsername = preferredUsername;
  }


  public AccessTokenDto profile(String profile) {
    
    this.profile = profile;
    return this;
  }

   /**
   * Get profile
   * @return profile
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProfile() {
    return profile;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfile(String profile) {
    this.profile = profile;
  }


  public AccessTokenDto realmAccess(AccessTokenAccessDto realmAccess) {
    
    this.realmAccess = realmAccess;
    return this;
  }

   /**
   * Get realmAccess
   * @return realmAccess
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_REALM_ACCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccessTokenAccessDto getRealmAccess() {
    return realmAccess;
  }


  @JsonProperty(JSON_PROPERTY_REALM_ACCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRealmAccess(AccessTokenAccessDto realmAccess) {
    this.realmAccess = realmAccess;
  }


  public AccessTokenDto sHash(String sHash) {
    
    this.sHash = sHash;
    return this;
  }

   /**
   * Get sHash
   * @return sHash
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_S_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getsHash() {
    return sHash;
  }


  @JsonProperty(JSON_PROPERTY_S_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setsHash(String sHash) {
    this.sHash = sHash;
  }


  public AccessTokenDto scope(String scope) {
    
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScope() {
    return scope;
  }


  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(String scope) {
    this.scope = scope;
  }


  public AccessTokenDto sessionState(String sessionState) {
    
    this.sessionState = sessionState;
    return this;
  }

   /**
   * Get sessionState
   * @return sessionState
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SESSION_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionState() {
    return sessionState;
  }


  @JsonProperty(JSON_PROPERTY_SESSION_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionState(String sessionState) {
    this.sessionState = sessionState;
  }


  public AccessTokenDto sid(String sid) {
    
    this.sid = sid;
    return this;
  }

   /**
   * Get sid
   * @return sid
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSid() {
    return sid;
  }


  @JsonProperty(JSON_PROPERTY_SID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSid(String sid) {
    this.sid = sid;
  }


  public AccessTokenDto sub(String sub) {
    
    this.sub = sub;
    return this;
  }

   /**
   * Get sub
   * @return sub
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SUB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSub() {
    return sub;
  }


  @JsonProperty(JSON_PROPERTY_SUB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSub(String sub) {
    this.sub = sub;
  }


  public AccessTokenDto trustedCerts(List<String> trustedCerts) {
    
    this.trustedCerts = trustedCerts;
    return this;
  }

  public AccessTokenDto addTrustedCertsItem(String trustedCertsItem) {
    if (this.trustedCerts == null) {
      this.trustedCerts = new ArrayList<>();
    }
    this.trustedCerts.add(trustedCertsItem);
    return this;
  }

   /**
   * Get trustedCerts
   * @return trustedCerts
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TRUSTED_CERTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTrustedCerts() {
    return trustedCerts;
  }


  @JsonProperty(JSON_PROPERTY_TRUSTED_CERTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrustedCerts(List<String> trustedCerts) {
    this.trustedCerts = trustedCerts;
  }


  public AccessTokenDto typ(String typ) {
    
    this.typ = typ;
    return this;
  }

   /**
   * Get typ
   * @return typ
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TYP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTyp() {
    return typ;
  }


  @JsonProperty(JSON_PROPERTY_TYP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTyp(String typ) {
    this.typ = typ;
  }


  public AccessTokenDto updatedAt(Long updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(Long updatedAt) {
    this.updatedAt = updatedAt;
  }


  public AccessTokenDto website(String website) {
    
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_WEBSITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWebsite() {
    return website;
  }


  @JsonProperty(JSON_PROPERTY_WEBSITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebsite(String website) {
    this.website = website;
  }


  public AccessTokenDto zoneinfo(String zoneinfo) {
    
    this.zoneinfo = zoneinfo;
    return this;
  }

   /**
   * Get zoneinfo
   * @return zoneinfo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ZONEINFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getZoneinfo() {
    return zoneinfo;
  }


  @JsonProperty(JSON_PROPERTY_ZONEINFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZoneinfo(String zoneinfo) {
    this.zoneinfo = zoneinfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessTokenDto accessToken = (AccessTokenDto) o;
    return Objects.equals(this.acr, accessToken.acr) &&
        Objects.equals(this.address, accessToken.address) &&
        Objects.equals(this.allowedOrigins, accessToken.allowedOrigins) &&
        Objects.equals(this.atHash, accessToken.atHash) &&
        Objects.equals(this.authTime, accessToken.authTime) &&
        Objects.equals(this.authorization, accessToken.authorization) &&
        Objects.equals(this.azp, accessToken.azp) &&
        Objects.equals(this.birthdate, accessToken.birthdate) &&
        Objects.equals(this.cHash, accessToken.cHash) &&
        Objects.equals(this.category, accessToken.category) &&
        Objects.equals(this.claimsLocales, accessToken.claimsLocales) &&
        Objects.equals(this.cnf, accessToken.cnf) &&
        Objects.equals(this.email, accessToken.email) &&
        Objects.equals(this.emailVerified, accessToken.emailVerified) &&
        Objects.equals(this.exp, accessToken.exp) &&
        Objects.equals(this.familyName, accessToken.familyName) &&
        Objects.equals(this.gender, accessToken.gender) &&
        Objects.equals(this.givenName, accessToken.givenName) &&
        Objects.equals(this.iat, accessToken.iat) &&
        Objects.equals(this.iss, accessToken.iss) &&
        Objects.equals(this.jti, accessToken.jti) &&
        Objects.equals(this.locale, accessToken.locale) &&
        Objects.equals(this.middleName, accessToken.middleName) &&
        Objects.equals(this.name, accessToken.name) &&
        Objects.equals(this.nbf, accessToken.nbf) &&
        Objects.equals(this.nickname, accessToken.nickname) &&
        Objects.equals(this.nonce, accessToken.nonce) &&
        Objects.equals(this.otherClaims, accessToken.otherClaims) &&
        Objects.equals(this.phoneNumber, accessToken.phoneNumber) &&
        Objects.equals(this.phoneNumberVerified, accessToken.phoneNumberVerified) &&
        Objects.equals(this.picture, accessToken.picture) &&
        Objects.equals(this.preferredUsername, accessToken.preferredUsername) &&
        Objects.equals(this.profile, accessToken.profile) &&
        Objects.equals(this.realmAccess, accessToken.realmAccess) &&
        Objects.equals(this.sHash, accessToken.sHash) &&
        Objects.equals(this.scope, accessToken.scope) &&
        Objects.equals(this.sessionState, accessToken.sessionState) &&
        Objects.equals(this.sid, accessToken.sid) &&
        Objects.equals(this.sub, accessToken.sub) &&
        Objects.equals(this.trustedCerts, accessToken.trustedCerts) &&
        Objects.equals(this.typ, accessToken.typ) &&
        Objects.equals(this.updatedAt, accessToken.updatedAt) &&
        Objects.equals(this.website, accessToken.website) &&
        Objects.equals(this.zoneinfo, accessToken.zoneinfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acr, address, allowedOrigins, atHash, authTime, authorization, azp, birthdate, cHash, category, claimsLocales, cnf, email, emailVerified, exp, familyName, gender, givenName, iat, iss, jti, locale, middleName, name, nbf, nickname, nonce, otherClaims, phoneNumber, phoneNumberVerified, picture, preferredUsername, profile, realmAccess, sHash, scope, sessionState, sid, sub, trustedCerts, typ, updatedAt, website, zoneinfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessTokenDto {\n");
    sb.append("    acr: ").append(toIndentedString(acr)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    allowedOrigins: ").append(toIndentedString(allowedOrigins)).append("\n");
    sb.append("    atHash: ").append(toIndentedString(atHash)).append("\n");
    sb.append("    authTime: ").append(toIndentedString(authTime)).append("\n");
    sb.append("    authorization: ").append(toIndentedString(authorization)).append("\n");
    sb.append("    azp: ").append(toIndentedString(azp)).append("\n");
    sb.append("    birthdate: ").append(toIndentedString(birthdate)).append("\n");
    sb.append("    cHash: ").append(toIndentedString(cHash)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    claimsLocales: ").append(toIndentedString(claimsLocales)).append("\n");
    sb.append("    cnf: ").append(toIndentedString(cnf)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    emailVerified: ").append(toIndentedString(emailVerified)).append("\n");
    sb.append("    exp: ").append(toIndentedString(exp)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    iat: ").append(toIndentedString(iat)).append("\n");
    sb.append("    iss: ").append(toIndentedString(iss)).append("\n");
    sb.append("    jti: ").append(toIndentedString(jti)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nbf: ").append(toIndentedString(nbf)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    otherClaims: ").append(toIndentedString(otherClaims)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    phoneNumberVerified: ").append(toIndentedString(phoneNumberVerified)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    preferredUsername: ").append(toIndentedString(preferredUsername)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    realmAccess: ").append(toIndentedString(realmAccess)).append("\n");
    sb.append("    sHash: ").append(toIndentedString(sHash)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    sessionState: ").append(toIndentedString(sessionState)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    sub: ").append(toIndentedString(sub)).append("\n");
    sb.append("    trustedCerts: ").append(toIndentedString(trustedCerts)).append("\n");
    sb.append("    typ: ").append(toIndentedString(typ)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    zoneinfo: ").append(toIndentedString(zoneinfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

