/*
 * ${product.name.full} Admin REST API
 * This is a REST API reference for the ${product.name.full} Admin REST API.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.mbo.keycloak.admin.api.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * AccessTokenCertConfDto
 */
@JsonPropertyOrder({
  AccessTokenCertConfDto.JSON_PROPERTY_X5T_HASH_S256
})
@JsonTypeName("AccessToken-CertConf")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AccessTokenCertConfDto {
  public static final String JSON_PROPERTY_X5T_HASH_S256 = "x5t#S256";
  private String x5tHashS256;

  public AccessTokenCertConfDto() {
  }

  public AccessTokenCertConfDto x5tHashS256(String x5tHashS256) {
    
    this.x5tHashS256 = x5tHashS256;
    return this;
  }

   /**
   * Get x5tHashS256
   * @return x5tHashS256
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_X5T_HASH_S256)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getX5tHashS256() {
    return x5tHashS256;
  }


  @JsonProperty(JSON_PROPERTY_X5T_HASH_S256)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setX5tHashS256(String x5tHashS256) {
    this.x5tHashS256 = x5tHashS256;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessTokenCertConfDto accessTokenCertConf = (AccessTokenCertConfDto) o;
    return Objects.equals(this.x5tHashS256, accessTokenCertConf.x5tHashS256);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x5tHashS256);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessTokenCertConfDto {\n");
    sb.append("    x5tHashS256: ").append(toIndentedString(x5tHashS256)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

