/*
 * ${product.name.full} Admin REST API
 * This is a REST API reference for the ${product.name.full} Admin REST API.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.mbo.keycloak.admin.api.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * AccessTokenAccessDto
 */
@JsonPropertyOrder({
  AccessTokenAccessDto.JSON_PROPERTY_ROLES,
  AccessTokenAccessDto.JSON_PROPERTY_VERIFY_CALLER
})
@JsonTypeName("AccessToken-Access")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AccessTokenAccessDto {
  public static final String JSON_PROPERTY_ROLES = "roles";
  private List<String> roles = null;

  public static final String JSON_PROPERTY_VERIFY_CALLER = "verify_caller";
  private Boolean verifyCaller;

  public AccessTokenAccessDto() {
  }

  public AccessTokenAccessDto roles(List<String> roles) {
    
    this.roles = roles;
    return this;
  }

  public AccessTokenAccessDto addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRoles() {
    return roles;
  }


  @JsonProperty(JSON_PROPERTY_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoles(List<String> roles) {
    this.roles = roles;
  }


  public AccessTokenAccessDto verifyCaller(Boolean verifyCaller) {
    
    this.verifyCaller = verifyCaller;
    return this;
  }

   /**
   * Get verifyCaller
   * @return verifyCaller
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_VERIFY_CALLER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVerifyCaller() {
    return verifyCaller;
  }


  @JsonProperty(JSON_PROPERTY_VERIFY_CALLER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerifyCaller(Boolean verifyCaller) {
    this.verifyCaller = verifyCaller;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessTokenAccessDto accessTokenAccess = (AccessTokenAccessDto) o;
    return Objects.equals(this.roles, accessTokenAccess.roles) &&
        Objects.equals(this.verifyCaller, accessTokenAccess.verifyCaller);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roles, verifyCaller);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessTokenAccessDto {\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    verifyCaller: ").append(toIndentedString(verifyCaller)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

