/*
 * ${product.name.full} Admin REST API
 * This is a REST API reference for the ${product.name.full} Admin REST API.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.mbo.keycloak.admin.api.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto
 */
@JsonPropertyOrder({
  ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto.JSON_PROPERTY_CONTAINER_ID,
  ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto.JSON_PROPERTY_CONTAINER_NAME,
  ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto.JSON_PROPERTY_CONTAINER_TYPE,
  ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto.JSON_PROPERTY_MAPPER_ID,
  ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto.JSON_PROPERTY_MAPPER_NAME,
  ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto.JSON_PROPERTY_PROTOCOL_MAPPER
})
@JsonTypeName("ClientScopeEvaluateResource-ProtocolMapperEvaluationRepresentation")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto {
  public static final String JSON_PROPERTY_CONTAINER_ID = "containerId";
  private String containerId;

  public static final String JSON_PROPERTY_CONTAINER_NAME = "containerName";
  private String containerName;

  public static final String JSON_PROPERTY_CONTAINER_TYPE = "containerType";
  private String containerType;

  public static final String JSON_PROPERTY_MAPPER_ID = "mapperId";
  private String mapperId;

  public static final String JSON_PROPERTY_MAPPER_NAME = "mapperName";
  private String mapperName;

  public static final String JSON_PROPERTY_PROTOCOL_MAPPER = "protocolMapper";
  private String protocolMapper;

  public ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto() {
  }

  public ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto containerId(String containerId) {
    
    this.containerId = containerId;
    return this;
  }

   /**
   * Get containerId
   * @return containerId
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CONTAINER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContainerId() {
    return containerId;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainerId(String containerId) {
    this.containerId = containerId;
  }


  public ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto containerName(String containerName) {
    
    this.containerName = containerName;
    return this;
  }

   /**
   * Get containerName
   * @return containerName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CONTAINER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContainerName() {
    return containerName;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainerName(String containerName) {
    this.containerName = containerName;
  }


  public ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto containerType(String containerType) {
    
    this.containerType = containerType;
    return this;
  }

   /**
   * Get containerType
   * @return containerType
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CONTAINER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContainerType() {
    return containerType;
  }


  @JsonProperty(JSON_PROPERTY_CONTAINER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainerType(String containerType) {
    this.containerType = containerType;
  }


  public ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto mapperId(String mapperId) {
    
    this.mapperId = mapperId;
    return this;
  }

   /**
   * Get mapperId
   * @return mapperId
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MAPPER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMapperId() {
    return mapperId;
  }


  @JsonProperty(JSON_PROPERTY_MAPPER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMapperId(String mapperId) {
    this.mapperId = mapperId;
  }


  public ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto mapperName(String mapperName) {
    
    this.mapperName = mapperName;
    return this;
  }

   /**
   * Get mapperName
   * @return mapperName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MAPPER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMapperName() {
    return mapperName;
  }


  @JsonProperty(JSON_PROPERTY_MAPPER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMapperName(String mapperName) {
    this.mapperName = mapperName;
  }


  public ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto protocolMapper(String protocolMapper) {
    
    this.protocolMapper = protocolMapper;
    return this;
  }

   /**
   * Get protocolMapper
   * @return protocolMapper
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PROTOCOL_MAPPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProtocolMapper() {
    return protocolMapper;
  }


  @JsonProperty(JSON_PROPERTY_PROTOCOL_MAPPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProtocolMapper(String protocolMapper) {
    this.protocolMapper = protocolMapper;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto clientScopeEvaluateResourceProtocolMapperEvaluationRepresentation = (ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto) o;
    return Objects.equals(this.containerId, clientScopeEvaluateResourceProtocolMapperEvaluationRepresentation.containerId) &&
        Objects.equals(this.containerName, clientScopeEvaluateResourceProtocolMapperEvaluationRepresentation.containerName) &&
        Objects.equals(this.containerType, clientScopeEvaluateResourceProtocolMapperEvaluationRepresentation.containerType) &&
        Objects.equals(this.mapperId, clientScopeEvaluateResourceProtocolMapperEvaluationRepresentation.mapperId) &&
        Objects.equals(this.mapperName, clientScopeEvaluateResourceProtocolMapperEvaluationRepresentation.mapperName) &&
        Objects.equals(this.protocolMapper, clientScopeEvaluateResourceProtocolMapperEvaluationRepresentation.protocolMapper);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containerId, containerName, containerType, mapperId, mapperName, protocolMapper);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentationDto {\n");
    sb.append("    containerId: ").append(toIndentedString(containerId)).append("\n");
    sb.append("    containerName: ").append(toIndentedString(containerName)).append("\n");
    sb.append("    containerType: ").append(toIndentedString(containerType)).append("\n");
    sb.append("    mapperId: ").append(toIndentedString(mapperId)).append("\n");
    sb.append("    mapperName: ").append(toIndentedString(mapperName)).append("\n");
    sb.append("    protocolMapper: ").append(toIndentedString(protocolMapper)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

