/*
 * ${product.name.full} Admin REST API
 * This is a REST API reference for the ${product.name.full} Admin REST API.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.mbo.keycloak.admin.api.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * ClientInitialAccessPresentationDto
 */
@JsonPropertyOrder({
  ClientInitialAccessPresentationDto.JSON_PROPERTY_COUNT,
  ClientInitialAccessPresentationDto.JSON_PROPERTY_EXPIRATION,
  ClientInitialAccessPresentationDto.JSON_PROPERTY_ID,
  ClientInitialAccessPresentationDto.JSON_PROPERTY_REMAINING_COUNT,
  ClientInitialAccessPresentationDto.JSON_PROPERTY_TIMESTAMP,
  ClientInitialAccessPresentationDto.JSON_PROPERTY_TOKEN
})
@JsonTypeName("ClientInitialAccessPresentation")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ClientInitialAccessPresentationDto {
  public static final String JSON_PROPERTY_COUNT = "count";
  private Integer count;

  public static final String JSON_PROPERTY_EXPIRATION = "expiration";
  private Integer expiration;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_REMAINING_COUNT = "remainingCount";
  private Integer remainingCount;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private Integer timestamp;

  public static final String JSON_PROPERTY_TOKEN = "token";
  private String token;

  public ClientInitialAccessPresentationDto() {
  }

  public ClientInitialAccessPresentationDto count(Integer count) {
    
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCount() {
    return count;
  }


  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCount(Integer count) {
    this.count = count;
  }


  public ClientInitialAccessPresentationDto expiration(Integer expiration) {
    
    this.expiration = expiration;
    return this;
  }

   /**
   * Get expiration
   * @return expiration
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_EXPIRATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExpiration() {
    return expiration;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiration(Integer expiration) {
    this.expiration = expiration;
  }


  public ClientInitialAccessPresentationDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ClientInitialAccessPresentationDto remainingCount(Integer remainingCount) {
    
    this.remainingCount = remainingCount;
    return this;
  }

   /**
   * Get remainingCount
   * @return remainingCount
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_REMAINING_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRemainingCount() {
    return remainingCount;
  }


  @JsonProperty(JSON_PROPERTY_REMAINING_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemainingCount(Integer remainingCount) {
    this.remainingCount = remainingCount;
  }


  public ClientInitialAccessPresentationDto timestamp(Integer timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }


  public ClientInitialAccessPresentationDto token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToken() {
    return token;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientInitialAccessPresentationDto clientInitialAccessPresentation = (ClientInitialAccessPresentationDto) o;
    return Objects.equals(this.count, clientInitialAccessPresentation.count) &&
        Objects.equals(this.expiration, clientInitialAccessPresentation.expiration) &&
        Objects.equals(this.id, clientInitialAccessPresentation.id) &&
        Objects.equals(this.remainingCount, clientInitialAccessPresentation.remainingCount) &&
        Objects.equals(this.timestamp, clientInitialAccessPresentation.timestamp) &&
        Objects.equals(this.token, clientInitialAccessPresentation.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, expiration, id, remainingCount, timestamp, token);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientInitialAccessPresentationDto {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    remainingCount: ").append(toIndentedString(remainingCount)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

