/*
 * ${product.name.full} Admin REST API
 * This is a REST API reference for the ${product.name.full} Admin REST API.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.mbo.keycloak.admin.api.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * ProtocolMapperRepresentationDto
 */
@JsonPropertyOrder({
  ProtocolMapperRepresentationDto.JSON_PROPERTY_CONFIG,
  ProtocolMapperRepresentationDto.JSON_PROPERTY_ID,
  ProtocolMapperRepresentationDto.JSON_PROPERTY_NAME,
  ProtocolMapperRepresentationDto.JSON_PROPERTY_PROTOCOL,
  ProtocolMapperRepresentationDto.JSON_PROPERTY_PROTOCOL_MAPPER
})
@JsonTypeName("ProtocolMapperRepresentation")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ProtocolMapperRepresentationDto {
  public static final String JSON_PROPERTY_CONFIG = "config";
  private Map<String, Object> config = null;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PROTOCOL = "protocol";
  private String protocol;

  public static final String JSON_PROPERTY_PROTOCOL_MAPPER = "protocolMapper";
  private String protocolMapper;

  public ProtocolMapperRepresentationDto() {
  }

  public ProtocolMapperRepresentationDto config(Map<String, Object> config) {
    
    this.config = config;
    return this;
  }

  public ProtocolMapperRepresentationDto putConfigItem(String key, Object configItem) {
    if (this.config == null) {
      this.config = new HashMap<>();
    }
    this.config.put(key, configItem);
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getConfig() {
    return config;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfig(Map<String, Object> config) {
    this.config = config;
  }


  public ProtocolMapperRepresentationDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ProtocolMapperRepresentationDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ProtocolMapperRepresentationDto protocol(String protocol) {
    
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PROTOCOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProtocol() {
    return protocol;
  }


  @JsonProperty(JSON_PROPERTY_PROTOCOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }


  public ProtocolMapperRepresentationDto protocolMapper(String protocolMapper) {
    
    this.protocolMapper = protocolMapper;
    return this;
  }

   /**
   * Get protocolMapper
   * @return protocolMapper
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PROTOCOL_MAPPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProtocolMapper() {
    return protocolMapper;
  }


  @JsonProperty(JSON_PROPERTY_PROTOCOL_MAPPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProtocolMapper(String protocolMapper) {
    this.protocolMapper = protocolMapper;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProtocolMapperRepresentationDto protocolMapperRepresentation = (ProtocolMapperRepresentationDto) o;
    return Objects.equals(this.config, protocolMapperRepresentation.config) &&
        Objects.equals(this.id, protocolMapperRepresentation.id) &&
        Objects.equals(this.name, protocolMapperRepresentation.name) &&
        Objects.equals(this.protocol, protocolMapperRepresentation.protocol) &&
        Objects.equals(this.protocolMapper, protocolMapperRepresentation.protocolMapper);
  }

  @Override
  public int hashCode() {
    return Objects.hash(config, id, name, protocol, protocolMapper);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProtocolMapperRepresentationDto {\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    protocolMapper: ").append(toIndentedString(protocolMapper)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

