/*
 * ${product.name.full} Admin REST API
 * This is a REST API reference for the ${product.name.full} Admin REST API.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.mbo.keycloak.admin.api.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * UserFederationProviderRepresentationDto
 */
@JsonPropertyOrder({
  UserFederationProviderRepresentationDto.JSON_PROPERTY_CHANGED_SYNC_PERIOD,
  UserFederationProviderRepresentationDto.JSON_PROPERTY_CONFIG,
  UserFederationProviderRepresentationDto.JSON_PROPERTY_DISPLAY_NAME,
  UserFederationProviderRepresentationDto.JSON_PROPERTY_FULL_SYNC_PERIOD,
  UserFederationProviderRepresentationDto.JSON_PROPERTY_ID,
  UserFederationProviderRepresentationDto.JSON_PROPERTY_LAST_SYNC,
  UserFederationProviderRepresentationDto.JSON_PROPERTY_PRIORITY,
  UserFederationProviderRepresentationDto.JSON_PROPERTY_PROVIDER_NAME
})
@JsonTypeName("UserFederationProviderRepresentation")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UserFederationProviderRepresentationDto {
  public static final String JSON_PROPERTY_CHANGED_SYNC_PERIOD = "changedSyncPeriod";
  private Integer changedSyncPeriod;

  public static final String JSON_PROPERTY_CONFIG = "config";
  private Map<String, Object> config = null;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  private String displayName;

  public static final String JSON_PROPERTY_FULL_SYNC_PERIOD = "fullSyncPeriod";
  private Integer fullSyncPeriod;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_LAST_SYNC = "lastSync";
  private Integer lastSync;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  private Integer priority;

  public static final String JSON_PROPERTY_PROVIDER_NAME = "providerName";
  private String providerName;

  public UserFederationProviderRepresentationDto() {
  }

  public UserFederationProviderRepresentationDto changedSyncPeriod(Integer changedSyncPeriod) {
    
    this.changedSyncPeriod = changedSyncPeriod;
    return this;
  }

   /**
   * Get changedSyncPeriod
   * @return changedSyncPeriod
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CHANGED_SYNC_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getChangedSyncPeriod() {
    return changedSyncPeriod;
  }


  @JsonProperty(JSON_PROPERTY_CHANGED_SYNC_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChangedSyncPeriod(Integer changedSyncPeriod) {
    this.changedSyncPeriod = changedSyncPeriod;
  }


  public UserFederationProviderRepresentationDto config(Map<String, Object> config) {
    
    this.config = config;
    return this;
  }

  public UserFederationProviderRepresentationDto putConfigItem(String key, Object configItem) {
    if (this.config == null) {
      this.config = new HashMap<>();
    }
    this.config.put(key, configItem);
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getConfig() {
    return config;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfig(Map<String, Object> config) {
    this.config = config;
  }


  public UserFederationProviderRepresentationDto displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public UserFederationProviderRepresentationDto fullSyncPeriod(Integer fullSyncPeriod) {
    
    this.fullSyncPeriod = fullSyncPeriod;
    return this;
  }

   /**
   * Get fullSyncPeriod
   * @return fullSyncPeriod
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_FULL_SYNC_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFullSyncPeriod() {
    return fullSyncPeriod;
  }


  @JsonProperty(JSON_PROPERTY_FULL_SYNC_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullSyncPeriod(Integer fullSyncPeriod) {
    this.fullSyncPeriod = fullSyncPeriod;
  }


  public UserFederationProviderRepresentationDto id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public UserFederationProviderRepresentationDto lastSync(Integer lastSync) {
    
    this.lastSync = lastSync;
    return this;
  }

   /**
   * Get lastSync
   * @return lastSync
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_LAST_SYNC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLastSync() {
    return lastSync;
  }


  @JsonProperty(JSON_PROPERTY_LAST_SYNC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastSync(Integer lastSync) {
    this.lastSync = lastSync;
  }


  public UserFederationProviderRepresentationDto priority(Integer priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPriority() {
    return priority;
  }


  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  public UserFederationProviderRepresentationDto providerName(String providerName) {
    
    this.providerName = providerName;
    return this;
  }

   /**
   * Get providerName
   * @return providerName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_PROVIDER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProviderName() {
    return providerName;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderName(String providerName) {
    this.providerName = providerName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserFederationProviderRepresentationDto userFederationProviderRepresentation = (UserFederationProviderRepresentationDto) o;
    return Objects.equals(this.changedSyncPeriod, userFederationProviderRepresentation.changedSyncPeriod) &&
        Objects.equals(this.config, userFederationProviderRepresentation.config) &&
        Objects.equals(this.displayName, userFederationProviderRepresentation.displayName) &&
        Objects.equals(this.fullSyncPeriod, userFederationProviderRepresentation.fullSyncPeriod) &&
        Objects.equals(this.id, userFederationProviderRepresentation.id) &&
        Objects.equals(this.lastSync, userFederationProviderRepresentation.lastSync) &&
        Objects.equals(this.priority, userFederationProviderRepresentation.priority) &&
        Objects.equals(this.providerName, userFederationProviderRepresentation.providerName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changedSyncPeriod, config, displayName, fullSyncPeriod, id, lastSync, priority, providerName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserFederationProviderRepresentationDto {\n");
    sb.append("    changedSyncPeriod: ").append(toIndentedString(changedSyncPeriod)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    fullSyncPeriod: ").append(toIndentedString(fullSyncPeriod)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastSync: ").append(toIndentedString(lastSync)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    providerName: ").append(toIndentedString(providerName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

